---

- hosts: eos
  become: yes
  roles:
    - requirements
    - deploy
    - testnet

  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python-minimal)

  vars:
    producer_name: eos_costa_rica
    p2p_address: 
    version: BETA
