---

 - name: clone repo eos
   become: yes
   apt:
     name: "{{ item }}"
     state: installed
     update_cache: yes
   with_items:
     - git
     - build-essential
     - python-simplejson
     - python-pexpect
